[build]
builder = "nixpacks"
buildCommand = "cd apps/web && npm install && npm run build"

[deploy]
startCommand = "cd apps/api && npm install && node server.cjs"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "8000"
